### ISSUE TITLE
Look Into Using Forms

### ISSUE THREAD

**Issue by AlexanderDefuria** [AlexanderDefuria/FRC-Scouting#91]
Look into using proper Django forms instead of the current solution.

Could improve troubleshooting and reliability. Also allows for the ability to write better tests.

**Comment by AlexanderDefuria** [comment]
Will run into issues with the uniqueness of each field and the icons associated with them.

The following must be satisfied.
- [x] Create drop downs
- [x] Comment boxes
- [x] Custom Increment Fields
- [x] Pass images to form components [Pass Parameters](https://stackoverflow.com/a/63945297/10560343)
- [x] Build Custom Widgets to maintain re-usability of our existing styles 
- [x] Combine components into groups

**Comment by AlexanderDefuria** [comment]
Need to rewrite validation process

**Comment by AlexanderDefuria** [comment]
Match scout is done now. Need to redo other forms now.

## Completed Forms
- [x] Match Scout
- [x] Pit Scout
- [x] Registration
- [x] Login
- [x] Import
- [ ] Settings

**Comment by AlexanderDefuria** [comment]
Settings forms should be redone later instead of now. Prefer to do after the org redo when substantial changes to the settings age will be made.
